export const iconNames = [
  "fingerprint",
  "star_rate",
  "face",
/*   "language",
  "lightbulb",
  "savings",
  "flutter_dash",
  "flight_land",
  "blender",
  "yard",
  "train",
  "music_note",
  "skateboarding",
  "emoji_food_beverage",
  "catching_pokemon",
  "interests",
  "rowing",
  "tsunami" */
];
